config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'friends#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'static_pages#home', as: :unauthenticated_root
    end
  end
  resources :friends
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/news'
  #get 'home/index'
  root 'friends#index'
  #root 'static_pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, exept: [:index]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
    #@friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)
    # @friend = current_user.friends.build

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized user" if @friend.nil?
  end  



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :user_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def news
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field form-group">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control", placeholder: "First Name" %>
  </div>

  <div class="field form-group ">
    <% form.label :last_name %>
    <%= form.text_field :last_name , class: "form-control", placeholder: "Last Name"%>
  </div>

  <div class="field form-group">
    <% form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>

  <div class="field form-group">
    <% form.label :phone %>
    <%= form.text_field :phone, class: "form-control", placeholder: "Phone" %>
  </div>
  <div class="field form-group">
    <%= form.text_field :user_id, id: :friend_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>
  
  <br/>
  <div class="actions">
    <%= form.submit class: "btn  btn-outline-success" %>
  </div>
  <br/>
<% end %>

app/views/friends/edit.html.erb
<h1 class="friend_h1">Editing Friend</h1>

<%= render 'form', friend: @friend %>

<div class="col">
    <div class="row">
        <%= link_to 'Show', @friend, class: "show-btn btn btn-outline-warning"  %> 
        <%= link_to 'Back', friends_path, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger ml-1" %>
    </div>
    <div class="row">
        <%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mt-2 d_button" %>
    </div>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>

  <h1 class = "friend_h1">Friends</h1>

  <table class="table table-striped border border-dark table-hover">
    <thead class="table_align thead-dark">
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th class= "hidden_el">Email</th>
        <th class= "hidden_el">Phone</th>
        <th colspan="2"  class= "hidden_el"></th>
        <th colspan ="1"></th>
      </tr>
    </thead>
    
    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
          <tr class="table_align" >
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>
            <td class= "hidden_el"><%= friend.email %></td>
            <td class= "hidden_el"><%= friend.phone %></td>
            <td><%= link_to 'Show', friend, class: "btn btn-secondary" %></td>
            <td class= "hidden_el"><%= link_to 'Edit', edit_friend_path(friend), class: "btn btn-dark" %></td>
            <td class= "hidden_el"><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
    
  </table>

  <br/>

  <%= link_to 'New Friend', new_friend_path, class: "new-btn btn btn-outline-success" %>
<% else %>
  <%= render 'static_pages/home' %>
<% end %>

app/views/friends/new.html.erb
<h1 class="friend_h1">New Friend</h1>
<br/>
<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger"%>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @friend.first_name %> <%= @friend.last_name %></h1>
  <p class="lead"><%= @friend.email %> | <%= @friend.phone %> | </p>
  <hr class="my-4">
  <div class="col">
    <div class="row-6">
      <%= link_to 'Edit', edit_friend_path(@friend), class: "show-btn btn btn-outline-warning" %>
      <%= link_to 'Back', friends_path, class: "show-btn btn btn-outline-danger ml-2 " %>
    </div>
    <div class="row-6">
      <%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mt-2 d_button" %>
    </div>
  </div>
  
  
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!Doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Logos -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
    <!-- Fonts-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@1,700&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lemonada:wght@500&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Newsreader:wght@500&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Friends</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render  'static_pages/header'%>
    <h1>Static text test</h1>
    <div class = "container">
      
    <% if notice %>
      <%= render 'layouts/alerts'%>
    <% end %>
      <%= yield %>
    </div>
    <i class="fal fa-sign-out-alt"></i>
    <p>Rails first test </p>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/static_pages/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="pl-2">
        <%= link_to 'Test', root_path, class: "main_logo navbar-brand rounded font-weight-bold bg-dark"%>
    </div>
   
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse pl-4 justify-content-between" id="navbarNavAltMarkup">
        <div class="navbar-nav">
        <% if user_signed_in? %>
            <%= link_to 'Friends', friends_path, class: "top_bar_text add_f nav-item nav-link ml-4 active"%>
            <%= link_to 'Add new friend', new_friend_path, class: "top_bar_text add_f nav-item nav-link ml-4"%>
        <% end %>
            <% if user_signed_in? %>
                <%= link_to 'Home', static_pages_home_path, class: 'top_bar_text add_f nav-item nav-link ml-4'%>
            <% else %>
                <%= link_to 'Home', static_pages_home_path, class: 'top_bar_text add_f nav-item nav-link ml-4 active'%>
            <% end %>
            <%= link_to 'News', static_pages_news_path, class: 'top_bar_text add_f nav-item nav-link ml-4'%>
            <%= link_to 'About Us' , static_pages_about_path, class: 'top_bar_text nav-item nav-link ml-4'%>
            <%= link_to 'Help', static_pages_help_path, class:'top_bar_text nav-item nav-link ml-4'%>
           
            <%# session password: qUWTP6UWJSmYGyg %>
            
            
        </div>
        <div class="row">
            <div class = "search_line">
                <form class="form-inline">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
            <div class="navbar-nav mr-1">
            <% if user_signed_in? %>
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "top_bar_text nav-item nav-link ml-4"%>
                <%= link_to 'Edit Profile', edit_user_registration_path, class: "top_bar_text nav-item nav-link ml-4"%>
            <% else %> 
                <%= link_to 'Sign Up', new_user_registration_path, class: " top_bar_text nav-item nav-link ml-4"%>
                <%= link_to 'Sign In', new_user_session_path, class: "top_bar_text nav-item nav-link ml-4"%>
            <% end %>
            </div>
        </div>
        
        
    </div>
</nav>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>About page</p>
<p>
The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
Tutorial</em></a> is a
<a href="http://www.railstutorial.org/book">book</a> and
<a href="http://screencasts.railstutorial.org/">screencast series</a>
to teach web development with
<a href="http://rubyonrails.org/">Ruby on Rails</a>.
This is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Help page</p>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Hello World!</h1>
<p>Home page</p>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/static_pages/news.html.erb
<h1>StaticPages#news</h1>
<p>News page</p>